name: mailjet_sender
version: 0.2.0
description: |
  Mailjet sender is a standalone dart library to send emails
    to.
homepage: https://github.com/jayjah/mailjet_sender
repository: https://github.com/jayjah/mailjet_sender.git

environment:
  sdk: '>=2.12.0'
  
dependencies:
  # http queries
  # BSD-License
  # https://pub.dev/packages/http
  http: ^0.13.0
dev_dependencies:
  test: ^1.16.5
  # analyzer rules
  pedantic: ^1.11.0

